export type IconName =
'' |
'accCircle' |
'accCirclePurple' |
'add' |
'addCircle' |
'addCirclePurple' |
'addGrey' |
'addPurple' |
'addReaction' |
'arrowDown' |
'arrowDownPurple' |
'arrowDrop' |
'arrowDropPurple' |
'arrowLeft' |
'arrowLeftPurple' |
'back' |
'backThinner' |
'check' |
'checkPurple' |
'close' |
'closePurple' |
'comment' |
'commentPurple' |
'edit' |
'editPencil' |
'editPencilPurple' |
'editPurple' |
'editWhite' |
'editWhiteThick' |
'email' |
'emailTag' |
'emailTagGrey' |
'emailTagPurple' |
'emoji' |
'emojiGrey' |
'emojiPurple' |
'flagAmerica' |
'flagGermany' |
'logout' |
'logoutPurple' |
'modeComment' |
'moreVert' |
'msg' |
'personAdd' |
'personAddPurple' |
'raisingHands' |
'reaction' |
'reactionPurple' |
'searchBlack' |
'searchGrey' |
'sendBlue' |
'sendHuge' |
'sendPurple' |
'tag' |
'tagGrey' |
'tagPurple' |
'whiteHeavyCheckmark' |
'workspaces' |
'workspacesPurple' |
'google' |
'user' |
'password' |
'mailReg' |
'dabubble-logo'
